import { indicatorsInformationBaseRoute } from "./base";

export const postAcademicProductionListsAuthorCareersRoute = indicatorsInformationBaseRoute + "/academicProductionListsAuthor/authorCareers"
export const updateAcademicProductionListsAuthorCareersRoute = indicatorsInformationBaseRoute + "/academicProductionListsAuthor/authorCareers"
export const getAcademicProductionListsAuthorsJoinedByAcademicProductionListID = indicatorsInformationBaseRoute + "/academicProductionListsAuthors/JoinedByAcademicProductionListID/"
export const getAcademicProductionListsAuthorPreviousCareersByAuthorID = indicatorsInformationBaseRoute + "/academicProductionListsAuthor/previousCareers/"