import { indicatorsInformationBaseRoute } from "./base";

export const postBookOrChaptersProductionListsAuthorRoute = indicatorsInformationBaseRoute + "/booksOrChaptersProductionListsAuthor"
export const updateBookOrChaptersProductionListsAuthorRoute = indicatorsInformationBaseRoute + "/booksOrChaptersProductionListsAuthor/authorCareers"
export const getBooksOrChaptersProductionListsAuthorsJoinedByBooksOrChaptersProductionListIDRoute = indicatorsInformationBaseRoute + "/booksOrChaptersProductionListsAuthors/JoinedByBooksOrChaptersProductionListID/"
